spring:
  mustache:
    suffix: .html
#    cache: false
#  devtools:
#    livereload:
#      enabled: true

app:
  youtube-api:
    app-key: AIzaSyB7a2QY3rC6LfufdC26l4m-UO3PisE970Q
    search-api: https://www.googleapis.com/youtube/v3/videos
    comment-api: https://www.googleapis.com/youtube/v3/commentThreads